name: Run Maven Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Maven Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: sonatype-nexus-snapshots
          server-username: NEXUS_OSS_USERNAME
          server-password: NEXUS_OSS_PASSWORD
      - name: Maven Build
        run: mvn clean verify sonar:sonar deploy -Pcoverage -Dsonar.organization=jaxxy-rs -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          NEXUS_OSS_USERNAME: ${{ secrets.NEXUS_OSS_USERNAME }}
          NEXUS_OSS_PASSWORD: ${{ secrets.NEXUS_OSS_PASSWORD }}
#      - name: Upload Maven build artifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: artifact
#          path: github-actions-java-maven/target/github-actions-java-maven.jar